version: "2"
linters:
  enable:
    - decorder
    - goconst
    - godox
    - gosec
    - whitespace
    - wsl_v5
  settings:
    decorder:
      dec-order:
        - type
        - const
        - var
        - func
    goconst:
      min-len: 2
      min-occurrences: 2
    unconvert:
      fast-math: true
      safe: true
    whitespace:
      multi-if: true
      multi-func: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      disable:
        - decl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
